"""update keluarga schema

Revision ID: 21dde1be1264
Revises: ae7ee1041f67
Create Date: 2026-06-04 16:22:04.935320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dde1be1264'
down_revision = 'ae7ee1041f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keluarga', sa.Column('umur_2026', sa.Integer(), nullable=True))
    op.add_column('keluarga', sa.Column('desil_nasional_anggota', sa.Integer(), nullable=True))
    op.add_column('keluarga', sa.Column('desil_nasional_keluarga', sa.Integer(), nullable=True))
    op.add_column('keluarga', sa.Column('cut_off_keluarga', sa.String(length=50), nullable=True))
    op.drop_column('keluarga', 'cut_off')
    op.drop_column('keluarga', 'kode_kelurahan_desa')
    op.drop_column('keluarga', 'kabupaten_kota')
    op.drop_column('keluarga', 'desil_nasional')
    op.drop_column('keluarga', 'id_pendapatan')
    op.drop_column('keluarga', 'kecamatan')
    op.drop_column('keluarga', 'kode_kecamatan')
    op.drop_column('keluarga', 'kelurahan_desa')
    op.drop_column('keluarga', 'kode_kabupaten_kota')
    op.drop_column('keluarga', 'nama_kepala_keluarga')
    op.drop_column('keluarga', 'alamat')
    op.drop_column('keluarga', 'provinsi')
    op.add_column('keluarga_history', sa.Column('umur_2026', sa.Integer(), nullable=True))
    op.add_column('keluarga_history', sa.Column('desil_nasional_anggota', sa.Integer(), nullable=True))
    op.add_column('keluarga_history', sa.Column('desil_nasional_keluarga', sa.Integer(), nullable=True))
    op.add_column('keluarga_history', sa.Column('cut_off_keluarga', sa.String(length=50), nullable=True))
    op.drop_column('keluarga_history', 'cut_off')
    op.drop_column('keluarga_history', 'kode_kelurahan_desa')
    op.drop_column('keluarga_history', 'kabupaten_kota')
    op.drop_column('keluarga_history', 'desil_nasional')
    op.drop_column('keluarga_history', 'id_pendapatan')
    op.drop_column('keluarga_history', 'kecamatan')
    op.drop_column('keluarga_history', 'kode_kecamatan')
    op.drop_column('keluarga_history', 'kelurahan_desa')
    op.drop_column('keluarga_history', 'kode_kabupaten_kota')
    op.drop_column('keluarga_history', 'nama_kepala_keluarga')
    op.drop_column('keluarga_history', 'alamat')
    op.drop_column('keluarga_history', 'provinsi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keluarga_history', sa.Column('provinsi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('alamat', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('nama_kepala_keluarga', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('kode_kabupaten_kota', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('kelurahan_desa', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('kode_kecamatan', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('kecamatan', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('id_pendapatan', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('desil_nasional', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('kabupaten_kota', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('kode_kelurahan_desa', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('keluarga_history', sa.Column('cut_off', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('keluarga_history', 'cut_off_keluarga')
    op.drop_column('keluarga_history', 'desil_nasional_keluarga')
    op.drop_column('keluarga_history', 'desil_nasional_anggota')
    op.drop_column('keluarga_history', 'umur_2026')
    op.add_column('keluarga', sa.Column('provinsi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('alamat', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('nama_kepala_keluarga', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('kode_kabupaten_kota', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('kelurahan_desa', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('kode_kecamatan', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('kecamatan', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('id_pendapatan', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('desil_nasional', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('kabupaten_kota', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('kode_kelurahan_desa', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('keluarga', sa.Column('cut_off', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('keluarga', 'cut_off_keluarga')
    op.drop_column('keluarga', 'desil_nasional_keluarga')
    op.drop_column('keluarga', 'desil_nasional_anggota')
    op.drop_column('keluarga', 'umur_2026')
    # ### end Alembic commands ###
