"""delete duplicate in table Keluarga

Revision ID: 6d1de8665444
Revises: 21dde1be1264
Create Date: 2026-06-07 15:10:00.662251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1de8665444'
down_revision = '21dde1be1264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keluarga', sa.Column('cut_off', sa.String(length=50), nullable=True))
    op.add_column('keluarga', sa.Column('desil_nasional', sa.Integer(), nullable=True))
    op.add_column('keluarga', sa.Column('provinsi', sa.String(length=100), nullable=True))
    op.add_column('keluarga', sa.Column('kode_kabupaten_kota', sa.String(length=50), nullable=True))
    op.add_column('keluarga', sa.Column('kabupaten_kota', sa.String(length=100), nullable=True))
    op.add_column('keluarga', sa.Column('kode_kecamatan', sa.String(length=50), nullable=True))
    op.add_column('keluarga', sa.Column('kecamatan', sa.String(length=100), nullable=True))
    op.add_column('keluarga', sa.Column('kode_kelurahan_desa', sa.String(length=50), nullable=True))
    op.add_column('keluarga', sa.Column('kelurahan_desa', sa.String(length=100), nullable=True))
    op.add_column('keluarga', sa.Column('alamat', sa.Text(), nullable=True))
    op.add_column('keluarga', sa.Column('nama_kepala_keluarga', sa.String(length=255), nullable=True))
    op.add_column('keluarga_history', sa.Column('cut_off', sa.String(length=50), nullable=True))
    op.add_column('keluarga_history', sa.Column('desil_nasional', sa.Integer(), nullable=True))
    op.add_column('keluarga_history', sa.Column('provinsi', sa.String(length=100), nullable=True))
    op.add_column('keluarga_history', sa.Column('kode_kabupaten_kota', sa.String(length=50), nullable=True))
    op.add_column('keluarga_history', sa.Column('kabupaten_kota', sa.String(length=100), nullable=True))
    op.add_column('keluarga_history', sa.Column('kode_kecamatan', sa.String(length=50), nullable=True))
    op.add_column('keluarga_history', sa.Column('kecamatan', sa.String(length=100), nullable=True))
    op.add_column('keluarga_history', sa.Column('kode_kelurahan_desa', sa.String(length=50), nullable=True))
    op.add_column('keluarga_history', sa.Column('kelurahan_desa', sa.String(length=100), nullable=True))
    op.add_column('keluarga_history', sa.Column('alamat', sa.Text(), nullable=True))
    op.add_column('keluarga_history', sa.Column('nama_kepala_keluarga', sa.String(length=255), nullable=True))
    op.drop_constraint('keluarga_history_no_kk_key', 'keluarga_history', type_='unique')
    op.drop_index('ix_keluarga_history_nik', table_name='keluarga_history')
    op.create_index(op.f('ix_keluarga_history_nik'), 'keluarga_history', ['nik'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keluarga_history_nik'), table_name='keluarga_history')
    op.create_index('ix_keluarga_history_nik', 'keluarga_history', ['nik'], unique=False)
    op.create_unique_constraint('keluarga_history_no_kk_key', 'keluarga_history', ['no_kk'])
    op.drop_column('keluarga_history', 'nama_kepala_keluarga')
    op.drop_column('keluarga_history', 'alamat')
    op.drop_column('keluarga_history', 'kelurahan_desa')
    op.drop_column('keluarga_history', 'kode_kelurahan_desa')
    op.drop_column('keluarga_history', 'kecamatan')
    op.drop_column('keluarga_history', 'kode_kecamatan')
    op.drop_column('keluarga_history', 'kabupaten_kota')
    op.drop_column('keluarga_history', 'kode_kabupaten_kota')
    op.drop_column('keluarga_history', 'provinsi')
    op.drop_column('keluarga_history', 'desil_nasional')
    op.drop_column('keluarga_history', 'cut_off')
    op.drop_column('keluarga', 'nama_kepala_keluarga')
    op.drop_column('keluarga', 'alamat')
    op.drop_column('keluarga', 'kelurahan_desa')
    op.drop_column('keluarga', 'kode_kelurahan_desa')
    op.drop_column('keluarga', 'kecamatan')
    op.drop_column('keluarga', 'kode_kecamatan')
    op.drop_column('keluarga', 'kabupaten_kota')
    op.drop_column('keluarga', 'kode_kabupaten_kota')
    op.drop_column('keluarga', 'provinsi')
    op.drop_column('keluarga', 'desil_nasional')
    op.drop_column('keluarga', 'cut_off')
    # ### end Alembic commands ###
