"""drop skor_prioritas

Revision ID: ae7ee1041f67
Revises: f8a2f6388778
Create Date: 2026-05-29 14:32:10.733811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7ee1041f67'
down_revision = 'f8a2f6388778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perhitungan', 'skor_prioritas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perhitungan', sa.Column('skor_prioritas', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
