"""inisialisasi tabel awal

Revision ID: f8a2f6388778
Revises: 
Create Date: 2026-05-25 13:42:15.527351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a2f6388778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perhitungan', 'reasoning_tim1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perhitungan', sa.Column('reasoning_tim1', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
