import uuid
from datetime import datetime
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, SmallInteger, JSON, DateTime, Text, Float
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from database import Base


# --- TABEL 1: USER (UNTUK LOGIN) ---
class User(Base):
    __tablename__ = "user"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    password_hash = Column(String)
    role = Column(String(20), default="ANALIS", nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    dibuat_pada = Column(DateTime, default=datetime.utcnow, nullable=False)

# --- TABEL 2: KELUARGA (MASTER DATA) ---
class Keluarga(Base):
    __tablename__ = "keluarga"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    nomor_kartu_keluarga = Column(String(100), nullable=False, index=True)
    periode              = Column(String(10), nullable=True, index=True)
    kode_provinsi           = Column(String(10))
    provinsi                = Column(String(100))
    kode_kabupaten_kota     = Column(String(15))
    kabupaten_kota          = Column(String(100))
    kode_kecamatan          = Column(String(20))
    kecamatan               = Column(String(100))
    kode_kelurahan_desa     = Column(String(25))
    kelurahan_desa          = Column(String(100))
    alamat                  = Column(String(500))
    jumlah_anggota_keluarga = Column(Integer)
    nama_anggota_keluarga   = Column(String(500))
    pbi_nas                 = Column(Boolean)
    pbi_pemda               = Column(Boolean)
    id_pelanggan_pln        = Column(String(20), nullable=True)
    status_kepemilikan_rumah  = Column(SmallInteger)
    jenis_lantai_terluas      = Column(SmallInteger)
    luas_lantai               = Column(Integer)
    jenis_dinding_terluas     = Column(SmallInteger)
    jenis_atap_terluas        = Column(SmallInteger)
    sumber_air_minum_utama    = Column(SmallInteger)
    sumber_penerangan_utama   = Column(SmallInteger)
    daya_terpasang            = Column(SmallInteger)
    bahan_bakar_utama_memasak = Column(SmallInteger)
    fasilitas_bab             = Column(SmallInteger)
    jenis_kloset              = Column(SmallInteger)
    pembuangan_akhir_tinja    = Column(SmallInteger)
    kepemilikan_aset                      = Column(Boolean)
    aset_bergerak_tabung_gas              = Column(Boolean)
    aset_bergerak_lemari_es               = Column(Boolean)
    aset_bergerak_ac                      = Column(Boolean)
    aset_bergerak_pemanas_air             = Column(Boolean)
    aset_bergerak_telepon_rumah           = Column(Boolean)
    aset_bergerak_tv_datar                = Column(Boolean)
    aset_bergerak_emas_perhiasan          = Column(Boolean)
    aset_bergerak_komputer_laptop_tablet  = Column(Boolean)
    aset_bergerak_sepeda_motor            = Column(Boolean)
    aset_bergerak_sepeda                  = Column(Boolean)
    aset_bergerak_mobil                   = Column(Boolean)
    aset_bergerak_perahu                  = Column(Boolean)
    aset_bergerak_kapal_perahu_motor      = Column(Boolean)
    aset_bergerak_smartphone              = Column(Boolean)
    aset_tidak_bergerak_lahan_lainnya     = Column(Boolean)
    aset_tidak_bergerak_rumah_lainnya     = Column(Boolean)
    jumlah_ternak_sapi          = Column(Integer)
    jumlah_ternak_kerbau        = Column(Integer)
    jumlah_ternak_kuda          = Column(Integer)
    jumlah_ternak_babi          = Column(Integer)
    jumlah_ternak_kambing_domba = Column(Integer)
    desil_nasional = Column(Integer, nullable=True)

# --- TABEL 3: KELUARGA_HISTORY
class KeluargaHistory(Base):
    __tablename__ = "keluarga_history"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    keluarga_id = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    nomor_kartu_keluarga = Column(String(16), nullable=False, index=True)
    periode              = Column(String(10), nullable=True, index=True)
    kode_provinsi           = Column(String(10))
    provinsi                = Column(String(100))
    kode_kabupaten_kota     = Column(String(15))
    kabupaten_kota          = Column(String(100))
    kode_kecamatan          = Column(String(20))
    kecamatan               = Column(String(100))
    kode_kelurahan_desa     = Column(String(25))
    kelurahan_desa          = Column(String(100))
    alamat                  = Column(String(500))
    jumlah_anggota_keluarga = Column(Integer)
    nama_anggota_keluarga   = Column(String(500))
    pbi_nas                 = Column(Boolean)
    pbi_pemda               = Column(Boolean)
    id_pelanggan_pln        = Column(String(20), nullable=True)
    status_kepemilikan_rumah  = Column(SmallInteger)
    jenis_lantai_terluas      = Column(SmallInteger)
    luas_lantai               = Column(Integer)
    jenis_dinding_terluas     = Column(SmallInteger)
    jenis_atap_terluas        = Column(SmallInteger)
    sumber_air_minum_utama    = Column(SmallInteger)
    sumber_penerangan_utama   = Column(SmallInteger)
    daya_terpasang            = Column(SmallInteger)
    bahan_bakar_utama_memasak = Column(SmallInteger)
    fasilitas_bab             = Column(SmallInteger)
    jenis_kloset              = Column(SmallInteger)
    pembuangan_akhir_tinja    = Column(SmallInteger)
    kepemilikan_aset                      = Column(Boolean)
    aset_bergerak_tabung_gas              = Column(Boolean)
    aset_bergerak_lemari_es               = Column(Boolean)
    aset_bergerak_ac                      = Column(Boolean)
    aset_bergerak_pemanas_air             = Column(Boolean)
    aset_bergerak_telepon_rumah           = Column(Boolean)
    aset_bergerak_tv_datar                = Column(Boolean)
    aset_bergerak_emas_perhiasan          = Column(Boolean)
    aset_bergerak_komputer_laptop_tablet  = Column(Boolean)
    aset_bergerak_sepeda_motor            = Column(Boolean)
    aset_bergerak_sepeda                  = Column(Boolean)
    aset_bergerak_mobil                   = Column(Boolean)
    aset_bergerak_perahu                  = Column(Boolean)
    aset_bergerak_kapal_perahu_motor      = Column(Boolean)
    aset_bergerak_smartphone              = Column(Boolean)
    aset_tidak_bergerak_lahan_lainnya     = Column(Boolean)
    aset_tidak_bergerak_rumah_lainnya     = Column(Boolean)
    jumlah_ternak_sapi          = Column(Integer)
    jumlah_ternak_kerbau        = Column(Integer)
    jumlah_ternak_kuda          = Column(Integer)
    jumlah_ternak_babi          = Column(Integer)
    jumlah_ternak_kambing_domba = Column(Integer)
    desil_nasional = Column(Integer, nullable=True)
 
    diarsipkan_pada = Column(DateTime, default=datetime.utcnow, nullable=False)

# --- TABEL 4: PERHITUNGAN (HASIL AI) ---
class Perhitungan(Base):
    __tablename__ = "perhitungan"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    keluarga_id = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    user_id     = Column(UUID(as_uuid=True), ForeignKey("user.id"), nullable=True)
    periode_asesmen = Column(String(10), nullable=True)
    diasesmen_pada  = Column(DateTime, default=datetime.utcnow)
    foto_id_digunakan          = Column(UUID(as_uuid=True), ForeignKey("foto.id"), nullable=True)
    reasoning_tim2             = Column(Text, nullable=True)
    ada_ketidaksesuaian_visual = Column(Boolean, nullable=True)
    reasoning_tim1   = Column(Text, nullable=True)
    desil_kemiskinan = Column(String(5), nullable=True)
    skor_prioritas   = Column(Integer, nullable=True)
    skor_aspd        = Column(Float, nullable=True)
    skor_pkht        = Column(Float, nullable=True)
    reasoning_tim3      = Column(Text, nullable=True)
    rekomendasi_bantuan = Column(JSONB, nullable=True)
    status_validasi = Column(String(20), default="Menunggu", nullable=False)
    catatan_petugas = Column(String(500), nullable=True)
    catatan_supervisor = Column(String(500), nullable=True)

# --- TABEL 5: FOTO RUMAH (MENGHUBUNGKAN KELUARGA DENGAN FOTO) ---
class Foto(Base):
    __tablename__ = "foto"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    keluarga_id = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    url_foto       = Column(String(500), nullable=False)
    periode        = Column(String(10), nullable=True, index=True)
    sumber         = Column(String(20), default="dtsen", nullable=False)
    nama_file_asli = Column(String(200), nullable=True)
    diunggah_pada  = Column(DateTime, default=datetime.utcnow, nullable=False)

# --- TABEL 6: LOG HISTORI (AUDIT TRAIL BANTUAN) ---
class LogHistori(Base):
    __tablename__ = "log_histori"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    keluarga_id = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    user_id     = Column(UUID(as_uuid=True), ForeignKey("user.id"), nullable=True)
    timestamp   = Column(DateTime, default=datetime.utcnow)
    
    desil_lama   = Column(String(5), nullable=True)
    desil_baru   = Column(String(5), nullable=True)
    bantuan_lama = Column(JSONB, nullable=True)
    bantuan_baru = Column(JSONB, nullable=True)
    keterangan   = Column(String(500), nullable=True)