import uuid
from datetime import datetime
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, SmallInteger, JSON, DateTime, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from database import Base


# --- TABEL 1: USER (UNTUK LOGIN) ---
class User(Base):
    __tablename__ = "user"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    password_hash = Column(String)

# --- TABEL 2: KELUARGA (DATA UTAMA) ---
class Keluarga(Base):
    __tablename__ = "keluarga"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    nik = Column(String(100), unique=True, index=True, nullable=True)
    no_kk = Column(String(100), unique=True, nullable=False)
    nama = Column(String(255), nullable=True)
    tempat_lahir = Column(String(100), nullable=True)
    tanggal_lahir = Column(String(50), nullable=True)
    id_jenis_kelamin = Column(Integer, nullable=True)
    id_hub_kepala_keluarga = Column(Integer, nullable=True)
    id_disabilitas = Column(Integer, nullable=True)
    tingkat_disabilitas = Column(String(50), nullable=True)
    pbi = Column(Integer, nullable=True)
    id_status_perkawinan = Column(Integer, nullable=True)
    id_partisipasi_sekolah = Column(Integer, nullable=True)
    id_jenjang_pendidikan_dukcapil = Column(Integer, nullable=True)
    membantu_bekerja = Column(Integer, nullable=True)
    id_lapangan_usaha_dari_usaha_utama = Column(Integer, nullable=True)
    id_status_kedudukan_pekerjaan_utama = Column(Integer, nullable=True)
    id_kepemilikan_izin_usaha = Column(Integer, nullable=True)
    jumlah_jenis_usaha = Column(Integer, nullable=True)
    id_pekerjaan_utama = Column(Integer, nullable=True)
    id_pendapatan = Column(Integer, nullable=True)
    jumlah_pekerja_dibayar = Column(Integer, nullable=True)
    jumlah_pekerja_tidak_dibayar = Column(Integer, nullable=True)
    id_omset_usaha_utama = Column(Integer, nullable=True)
    id_kondisi_gizi = Column(Integer, nullable=True)
    id_penglihatan = Column(Integer, nullable=True)
    id_pendengaran = Column(Integer, nullable=True)
    id_berjalan_atau_naik_tangga = Column(Integer, nullable=True)
    id_menggunakan_tangan_jari = Column(Integer, nullable=True)
    id_belajar_kemampuan_intelektual = Column(Integer, nullable=True)
    id_pengendalian_perilaku = Column(Integer, nullable=True)
    id_berbicara_komunikasi = Column(Integer, nullable=True)
    id_mengurus_diri = Column(Integer, nullable=True)
    id_mengingat_berkonsentrasi = Column(Integer, nullable=True)
    id_kesedihan_depresi = Column(Integer, nullable=True)
    id_penyakit_menahun = Column(Integer, nullable=True)
    status_dtsen = Column(String(100), nullable=True)
    cut_off = Column(String(50), nullable=True)
    desil_nasional = Column(Integer, nullable=True)
    kpm_jawara = Column(Integer, nullable=True)
    putri_jawara = Column(Integer, nullable=True)
    aspd = Column(Integer, nullable=True)
    eks_ppks_jawara = Column(Integer, nullable=True)
    ppks_jawara = Column(Integer, nullable=True)
    kemiskinan_ekstrem = Column(Integer, nullable=True)
    pkh_plus = Column(Integer, nullable=True)
    kode_provinsi = Column(String(10), nullable=True)
    provinsi = Column(String(100), nullable=True)
    kode_kabupaten_kota = Column(String(10), nullable=True)
    kabupaten_kota = Column(String(100), nullable=True)
    kode_kecamatan = Column(String(10), nullable=True)
    kecamatan = Column(String(100), nullable=True)
    kode_kelurahan_desa = Column(String(10), nullable=True)
    kelurahan_desa = Column(String(100), nullable=True)
    alamat = Column(Text, nullable=True)
    nama_kepala_keluarga = Column(String(255), nullable=True)
    id_status_keberadaan_keluarga = Column(Integer, nullable=True)
    id_dayapenerangan = Column(Integer, nullable=True)
    jumlah_anggota_keluarga = Column(Integer, nullable=True)
    id_status_penguasaan_bangunan = Column(Integer, nullable=True)
    id_lantai_terluas = Column(Integer, nullable=True)
    luas_lantai_bangunan = Column(Integer, nullable=True)
    id_dinding_terluas = Column(Integer, nullable=True)
    id_atap_terluas = Column(Integer, nullable=True)
    id_sumber_airminum = Column(Integer, nullable=True)
    id_sumberpenerangan = Column(Integer, nullable=True)
    id_bb_utama = Column(Integer, nullable=True)
    id_fasilitas_bab = Column(Integer, nullable=True)
    id_jenis_kloset = Column(Integer, nullable=True)
    id_pembuangan_tinja = Column(Integer, nullable=True)
    kepemilikan_aset = Column(Integer, nullable=True)
    aset_bergerak_tabung_gas = Column(Integer, nullable=True)
    aset_bergerak_lemari_es = Column(Integer, nullable=True)
    aset_bergerak_ac = Column(Integer, nullable=True)
    aset_bergerak_pemanas_air = Column(Integer, nullable=True)
    aset_bergerak_telepon_rumah = Column(Integer, nullable=True)
    aset_bergerak_tv_datar = Column(Integer, nullable=True)
    aset_bergerak_emas_perhiasan = Column(Integer, nullable=True)
    aset_bergerak_komputer_laptop_tablet = Column(Integer, nullable=True)
    aset_bergerak_sepeda_motor = Column(Integer, nullable=True)
    aset_bergerak_sepeda = Column(Integer, nullable=True)
    aset_bergerak_mobil = Column(Integer, nullable=True)
    aset_bergerak_perahu = Column(Integer, nullable=True)
    aset_bergerak_kapal_perahu_motor = Column(Integer, nullable=True)
    aset_bergerak_smartphone = Column(Integer, nullable=True)
    lahan_tempat_lain = Column(Integer, nullable=True)
    rumah_tempat_lain = Column(Integer, nullable=True)
    jml_sapi = Column(Integer, nullable=True)
    jml_kerbau = Column(Integer, nullable=True)
    jml_kuda = Column(Integer, nullable=True)
    jml_babi = Column(Integer, nullable=True)
    jml_kambing_domba = Column(Integer, nullable=True)
    bansos = Column(Text, nullable=True)

# --- TABEL 3: KELUARGA_HISTORY
class KeluargaHistory(Base):
    __tablename__ = "keluarga_history"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    id_keluarga = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    nik = Column(String(100), unique=True, index=True, nullable=True)
    no_kk = Column(String(100), unique=True, nullable=False)
    nama = Column(String(255), nullable=True)
    tempat_lahir = Column(String(100), nullable=True)
    tanggal_lahir = Column(String(50), nullable=True)
    id_jenis_kelamin = Column(Integer, nullable=True)
    id_hub_kepala_keluarga = Column(Integer, nullable=True)
    id_disabilitas = Column(Integer, nullable=True)
    tingkat_disabilitas = Column(String(50), nullable=True)
    pbi = Column(Integer, nullable=True)
    id_status_perkawinan = Column(Integer, nullable=True)
    id_partisipasi_sekolah = Column(Integer, nullable=True)
    id_jenjang_pendidikan_dukcapil = Column(Integer, nullable=True)
    membantu_bekerja = Column(Integer, nullable=True)
    id_lapangan_usaha_dari_usaha_utama = Column(Integer, nullable=True)
    id_status_kedudukan_pekerjaan_utama = Column(Integer, nullable=True)
    id_kepemilikan_izin_usaha = Column(Integer, nullable=True)
    jumlah_jenis_usaha = Column(Integer, nullable=True)
    id_pekerjaan_utama = Column(Integer, nullable=True)
    id_pendapatan = Column(Integer, nullable=True)
    jumlah_pekerja_dibayar = Column(Integer, nullable=True)
    jumlah_pekerja_tidak_dibayar = Column(Integer, nullable=True)
    id_omset_usaha_utama = Column(Integer, nullable=True)
    id_kondisi_gizi = Column(Integer, nullable=True)
    id_penglihatan = Column(Integer, nullable=True)
    id_pendengaran = Column(Integer, nullable=True)
    id_berjalan_atau_naik_tangga = Column(Integer, nullable=True)
    id_menggunakan_tangan_jari = Column(Integer, nullable=True)
    id_belajar_kemampuan_intelektual = Column(Integer, nullable=True)
    id_pengendalian_perilaku = Column(Integer, nullable=True)
    id_berbicara_komunikasi = Column(Integer, nullable=True)
    id_mengurus_diri = Column(Integer, nullable=True)
    id_mengingat_berkonsentrasi = Column(Integer, nullable=True)
    id_kesedihan_depresi = Column(Integer, nullable=True)
    id_penyakit_menahun = Column(Integer, nullable=True)
    status_dtsen = Column(String(100), nullable=True)
    cut_off = Column(String(50), nullable=True)
    desil_nasional = Column(Integer, nullable=True)
    kpm_jawara = Column(Integer, nullable=True)
    putri_jawara = Column(Integer, nullable=True)
    aspd = Column(Integer, nullable=True)
    eks_ppks_jawara = Column(Integer, nullable=True)
    ppks_jawara = Column(Integer, nullable=True)
    kemiskinan_ekstrem = Column(Integer, nullable=True)
    pkh_plus = Column(Integer, nullable=True)
    kode_provinsi = Column(String(10), nullable=True)
    provinsi = Column(String(100), nullable=True)
    kode_kabupaten_kota = Column(String(10), nullable=True)
    kabupaten_kota = Column(String(100), nullable=True)
    kode_kecamatan = Column(String(10), nullable=True)
    kecamatan = Column(String(100), nullable=True)
    kode_kelurahan_desa = Column(String(10), nullable=True)
    kelurahan_desa = Column(String(100), nullable=True)
    alamat = Column(Text, nullable=True)
    nama_kepala_keluarga = Column(String(255), nullable=True)
    id_status_keberadaan_keluarga = Column(Integer, nullable=True)
    id_dayapenerangan = Column(Integer, nullable=True)
    jumlah_anggota_keluarga = Column(Integer, nullable=True)
    id_status_penguasaan_bangunan = Column(Integer, nullable=True)
    id_lantai_terluas = Column(Integer, nullable=True)
    luas_lantai_bangunan = Column(Integer, nullable=True)
    id_dinding_terluas = Column(Integer, nullable=True)
    id_atap_terluas = Column(Integer, nullable=True)
    id_sumber_airminum = Column(Integer, nullable=True)
    id_sumberpenerangan = Column(Integer, nullable=True)
    id_bb_utama = Column(Integer, nullable=True)
    id_fasilitas_bab = Column(Integer, nullable=True)
    id_jenis_kloset = Column(Integer, nullable=True)
    id_pembuangan_tinja = Column(Integer, nullable=True)
    kepemilikan_aset = Column(Integer, nullable=True)
    aset_bergerak_tabung_gas = Column(Integer, nullable=True)
    aset_bergerak_lemari_es = Column(Integer, nullable=True)
    aset_bergerak_ac = Column(Integer, nullable=True)
    aset_bergerak_pemanas_air = Column(Integer, nullable=True)
    aset_bergerak_telepon_rumah = Column(Integer, nullable=True)
    aset_bergerak_tv_datar = Column(Integer, nullable=True)
    aset_bergerak_emas_perhiasan = Column(Integer, nullable=True)
    aset_bergerak_komputer_laptop_tablet = Column(Integer, nullable=True)
    aset_bergerak_sepeda_motor = Column(Integer, nullable=True)
    aset_bergerak_sepeda = Column(Integer, nullable=True)
    aset_bergerak_mobil = Column(Integer, nullable=True)
    aset_bergerak_perahu = Column(Integer, nullable=True)
    aset_bergerak_kapal_perahu_motor = Column(Integer, nullable=True)
    aset_bergerak_smartphone = Column(Integer, nullable=True)
    lahan_tempat_lain = Column(Integer, nullable=True)
    rumah_tempat_lain = Column(Integer, nullable=True)
    jml_sapi = Column(Integer, nullable=True)
    jml_kerbau = Column(Integer, nullable=True)
    jml_kuda = Column(Integer, nullable=True)
    jml_babi = Column(Integer, nullable=True)
    jml_kambing_domba = Column(Integer, nullable=True)
    bansos = Column(Text, nullable=True)

    diarsipkan_pada = Column(DateTime, default=datetime.utcnow, nullable=False)

# --- TABEL 4: PERHITUNGAN (HASIL AI) ---
class Perhitungan(Base):
    __tablename__ = "perhitungan"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    keluarga_id = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    user_id     = Column(UUID(as_uuid=True), ForeignKey("user.id"), nullable=True)
    periode_asesmen = Column(String(10), nullable=True)
    diasesmen_pada  = Column(DateTime, default=datetime.utcnow)
    foto_id_digunakan          = Column(UUID(as_uuid=True), ForeignKey("foto.id"), nullable=True)
    reasoning_tim2             = Column(Text, nullable=True)
    ada_ketidaksesuaian_visual = Column(Boolean, nullable=True)
    reasoning_tim1   = Column(Text, nullable=True)
    desil_kemiskinan = Column(String(5), nullable=True)
    skor_prioritas   = Column(Integer, nullable=True)
    reasoning_tim3      = Column(Text, nullable=True)
    rekomendasi_bantuan = Column(JSONB, nullable=True)
    status_validasi = Column(String(20), default="Menunggu", nullable=False)
    catatan_petugas = Column(String(500), nullable=True)

# --- TABEL 5: FOTO RUMAH (MENGHUBUNGKAN KELUARGA DENGAN FOTO) ---
class Foto(Base):
    __tablename__ = "foto"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    keluarga_id = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    url_foto       = Column(String(500), nullable=False)
    tampak_dalam   = Column(Boolean, default=False)
    periode        = Column(String(10), nullable=True, index=True)
    sumber         = Column(String(20), default="dtsen", nullable=False)
    nama_file_asli = Column(String(200), nullable=True)
    diunggah_pada  = Column(DateTime, default=datetime.utcnow, nullable=False)

# --- TABEL 6: LOG HISTORI (AUDIT TRAIL BANTUAN) ---
class LogHistori(Base):
    __tablename__ = "log_histori"
    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    keluarga_id = Column(UUID(as_uuid=True), ForeignKey("keluarga.id"), nullable=False, index=True)
    user_id     = Column(UUID(as_uuid=True), ForeignKey("user.id"), nullable=True)
    timestamp   = Column(DateTime, default=datetime.utcnow)
    desil_lama   = Column(String(5), nullable=True)
    desil_baru   = Column(String(5), nullable=True)
    bantuan_lama = Column(JSONB, nullable=True)
    bantuan_baru = Column(JSONB, nullable=True)
    keterangan   = Column(String(500), nullable=True)